swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: |
    ![Fake Image]'<img src="invalid.jpg" onerror="alert(\'Hello\')">'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
