swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: |
    ![Fake Image](https://s3-ap-southeast-1.amazonaws.com/bsy/iportal/images/airtel-logo-red-text-horizontal.jpg)
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
